from tkinter import *
import tkinter.messagebox
import customtkinter

customtkinter.set_appearance_mode("System")  # Modes: "System" (standard), "Dark", "Light"
customtkinter.set_default_color_theme("blue")  # Themes: "blue" (standard), "green", "dark-blue"


class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        self.title("KhPD MC Capacity")
        self.geometry(f"{2400}x{580}")


        self.label = customtkinter.CTkLabel(self, text="1", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=1, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="2", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=2, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="3", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=3, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="4", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=4, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="5", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=5, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="6", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=6, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="7", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=7, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="8", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=8, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="9", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=9, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="10", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=10, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="11", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=11, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="12", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=12, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="13", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=13, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="14", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=14, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="15", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=15, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="16", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=16, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="17", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=17, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="18", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=18, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="19", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=19, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="20", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=20, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="21", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=21, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="22", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=22, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="23", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=23, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="24", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=24, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="25", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=25, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="26", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=26, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="27", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=27, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="28", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=28, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="29", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=29, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="30", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=30, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="31", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=31, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="32", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=32, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="33", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=33, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="34", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=34, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="35", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=35, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="36", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=36, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="37", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=37, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="38", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=38, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="39", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=39, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="40", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=40, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="41", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=41, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="42", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=42, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="43", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=43, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="44", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=44, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="45", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=45, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="46", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=46, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="47", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=47, padx=20, pady=(20, 10))
        self.label = customtkinter.CTkLabel(self, text="48", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.label.grid(row=0, column=48, padx=20, pady=(20, 10))
        
        #self.grid_columnconfigure(1, weight=1)
        self.grid_columnconfigure((15, 18, 21, 27, 30, 33, 36, 39, 42, 45, 48), weight=1)
        self.grid_rowconfigure((0, 1, 2, 4, 5, 6), weight=1)

        self.sidebar_frame = customtkinter.CTkFrame(self, width=140, corner_radius=0)
        self.sidebar_frame.grid(row=0, column=0, rowspan=7, sticky="nsew")
        self.sidebar_frame.grid_rowconfigure(4, weight=1)
        self.logo_label = customtkinter.CTkLabel(self.sidebar_frame, text="Commands", font=customtkinter.CTkFont(size=20, weight="bold"))
        self.logo_label.grid(row=0, column=0, padx=20, pady=(20, 10))
        self.sidebar_button_1 = customtkinter.CTkButton(self.sidebar_frame, text="New Transaction", command=self.sidebar_button_event)
        self.sidebar_button_1.grid(row=1, column=0, padx=20, pady=10)
        self.sidebar_button_2 = customtkinter.CTkButton(self.sidebar_frame, text="History", command=self.sidebar_button_event)
        self.sidebar_button_2.grid(row=2, column=0, padx=20, pady=10)
        self.sidebar_button_3 = customtkinter.CTkButton(self.sidebar_frame, command=self.sidebar_button_event)
        self.sidebar_button_3.grid(row=3, column=0, padx=20, pady=10)
        self.appearance_mode_label = customtkinter.CTkLabel(self.sidebar_frame, text="Appearance Mode:", anchor="w")
        self.appearance_mode_label.grid(row=5, column=0, padx=20, pady=(10, 0))
        self.appearance_mode_optionemenu = customtkinter.CTkOptionMenu(self.sidebar_frame, values=["Light", "Dark", "System"],
                                                                       command=self.change_appearance_mode_event)
        self.appearance_mode_optionemenu.grid(row=6, column=0, padx=20, pady=(10, 10))
        self.scaling_label = customtkinter.CTkLabel(self.sidebar_frame, text="UI Scaling:", anchor="w")
        self.scaling_label.grid(row=7, column=0, padx=20, pady=(10, 0))
        self.scaling_optionemenu = customtkinter.CTkOptionMenu(self.sidebar_frame, values=["80%", "90%", "100%", "110%", "120%"],
                                                               command=self.change_scaling_event)
        self.scaling_optionemenu.grid(row=8, column=0, padx=20, pady=(10, 20))

        self.radio_var = tkinter.IntVar(value=0)
        self.sidebar_button_3.configure(state="disabled", text="Disabled CTkButton")

        self.appearance_mode_optionemenu.set("Dark")
        self.scaling_optionemenu.set("100%")
        
        self.M_frame = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.M_frame.grid(row=1, column=15, rowspan=7, padx=1, pady=1)
        
        self.L_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.L_frame1.grid(row=1, column=18, rowspan=3, columnspan=3, padx=1, pady=1)
        self.L_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.L_frame2.grid(row=4, column=18, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.K_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.K_frame1.grid(row=1, column=21, rowspan=3, columnspan=3, padx=1, pady=1)
        self.K_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.K_frame2.grid(row=4, column=21, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.J_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.J_frame1.grid(row=1, column=24, rowspan=3, columnspan=3, padx=1, pady=1)
        self.J_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.J_frame2.grid(row=4, column=24, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.H_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.H_frame1.grid(row=1, column=27, rowspan=3, columnspan=3, padx=1, pady=1)
        self.H_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.H_frame2.grid(row=4, column=27, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.G_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.G_frame1.grid(row=1, column=30, rowspan=3, columnspan=3, padx=1, pady=1)
        self.G_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.G_frame2.grid(row=4, column=30, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.F_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.F_frame1.grid(row=1, column=33, rowspan=3, columnspan=3, padx=1, pady=1)
        self.F_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.F_frame2.grid(row=4, column=33, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.E_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.E_frame1.grid(row=1, column=36, rowspan=3, columnspan=3, padx=1, pady=1)
        self.E_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.E_frame2.grid(row=4, column=36, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.D_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.D_frame1.grid(row=1, column=39, rowspan=3, columnspan=3, padx=1, pady=1)
        self.D_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.D_frame2.grid(row=4, column=39, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.C_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.C_frame1.grid(row=1, column=42, rowspan=3, columnspan=3, padx=1, pady=1)
        self.C_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.C_frame2.grid(row=4, column=42, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.B_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.B_frame1.grid(row=1, column=45, rowspan=3, columnspan=3, padx=1, pady=1)
        self.B_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.B_frame2.grid(row=4, column=45, rowspan=3, columnspan=3, padx=1, pady=1)
        
        self.A_frame1 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.A_frame1.grid(row=1, column=48, rowspan=3, columnspan=3, padx=1, pady=1)
        self.A_frame2 = customtkinter.CTkFrame(self, corner_radius=10, fg_color="grey")
        self.A_frame2.grid(row=4, column=48, rowspan=3, columnspan=3, padx=1, pady=1)

        
        # Shelves
        # A
        self.A01A1 = customtkinter.CTkButton(self.A_frame1, text='A01A1', command=self.sidebar_button_event, width=15)
        self.A01A1.grid(row=1, column=45, padx=3, pady=16, sticky="nsew")
        self.A01A2 = customtkinter.CTkButton(self.A_frame1, text='A01A2', command=self.sidebar_button_event, width=15)
        self.A01A2.grid(row=2, column=45, padx=3, pady=16, sticky="nsew")
        self.A01B1 = customtkinter.CTkButton(self.A_frame1, text='A01B1', command=self.sidebar_button_event, width=15)
        self.A01B1.grid(row=3, column=45, padx=3, pady=16, sticky="nsew")
        self.A01B2 = customtkinter.CTkButton(self.A_frame1, text='A01B2', command=self.sidebar_button_event, width=15)
        self.A01B2.grid(row=4, column=45, padx=3, pady=16, sticky="nsew")
        self.A01C1 = customtkinter.CTkButton(self.A_frame1, text='A01C1', command=self.sidebar_button_event, width=15)
        self.A01C1.grid(row=5, column=45, padx=3, pady=16, sticky="nsew")
        self.A01C2 = customtkinter.CTkButton(self.A_frame1, text='A01C2', command=self.sidebar_button_event, width=15)
        self.A01C2.grid(row=6, column=45, padx=3, pady=16, sticky="nsew")
        self.A01D1 = customtkinter.CTkButton(self.A_frame1, text='A01D1', command=self.sidebar_button_event, width=15)
        self.A01D1.grid(row=7, column=45, padx=3, pady=16, sticky="nsew")
        self.A01D2 = customtkinter.CTkButton(self.A_frame1, text='A01D2', command=self.sidebar_button_event, width=15)
        self.A01D2.grid(row=8, column=45, padx=3, pady=16, sticky="nsew")
        
        self.A02A1 = customtkinter.CTkButton(self.A_frame1, text='A02A1', command=self.sidebar_button_event, width=15)
        self.A02A1.grid(row=1, column=46, padx=3, pady=16, sticky="nsew")
        self.A02A2 = customtkinter.CTkButton(self.A_frame1, text='A02A2', command=self.sidebar_button_event, width=15)
        self.A02A2.grid(row=2, column=46, padx=3, pady=16, sticky="nsew")
        self.A02B1 = customtkinter.CTkButton(self.A_frame1, text='A02B1', command=self.sidebar_button_event, width=15)
        self.A02B1.grid(row=3, column=46, padx=3, pady=16, sticky="nsew")
        self.A02B2 = customtkinter.CTkButton(self.A_frame1, text='A02B2', command=self.sidebar_button_event, width=15)
        self.A02B2.grid(row=4, column=46, padx=3, pady=16, sticky="nsew")
        self.A02C1 = customtkinter.CTkButton(self.A_frame1, text='A02C1', command=self.sidebar_button_event, width=15)
        self.A02C1.grid(row=5, column=46, padx=3, pady=16, sticky="nsew")
        self.A02C2 = customtkinter.CTkButton(self.A_frame1, text='A02C2', command=self.sidebar_button_event, width=15)
        self.A02C2.grid(row=6, column=46, padx=3, pady=16, sticky="nsew")
        self.A02D1 = customtkinter.CTkButton(self.A_frame1, text='A02D1', command=self.sidebar_button_event, width=15)
        self.A02D1.grid(row=7, column=46, padx=3, pady=16, sticky="nsew")
        self.A02D2 = customtkinter.CTkButton(self.A_frame1, text='A02D2', command=self.sidebar_button_event, width=15)
        self.A02D2.grid(row=8, column=46, padx=3, pady=16, sticky="nsew")
        
        self.A03A1 = customtkinter.CTkButton(self.A_frame1, text='A03A1', command=self.sidebar_button_event, width=15)
        self.A03A1.grid(row=1, column=47, padx=3, pady=16, sticky="nsew")
        self.A03A2 = customtkinter.CTkButton(self.A_frame1, text='A03A2', command=self.sidebar_button_event, width=15)
        self.A03A2.grid(row=2, column=47, padx=3, pady=16, sticky="nsew")
        self.A03B1 = customtkinter.CTkButton(self.A_frame1, text='A03B1', command=self.sidebar_button_event, width=15)
        self.A03B1.grid(row=3, column=47, padx=3, pady=16, sticky="nsew")
        self.A03B2 = customtkinter.CTkButton(self.A_frame1, text='A03B2', command=self.sidebar_button_event, width=15)
        self.A03B2.grid(row=4, column=47, padx=3, pady=16, sticky="nsew")
        self.A03C1 = customtkinter.CTkButton(self.A_frame1, text='A03C1', command=self.sidebar_button_event, width=15)
        self.A03C1.grid(row=5, column=47, padx=3, pady=16, sticky="nsew")
        self.A03C2 = customtkinter.CTkButton(self.A_frame1, text='A03C2', command=self.sidebar_button_event, width=15)
        self.A03C2.grid(row=6, column=47, padx=3, pady=16, sticky="nsew")
        self.A03D1 = customtkinter.CTkButton(self.A_frame1, text='A03D1', command=self.sidebar_button_event, width=15)
        self.A03D1.grid(row=7, column=47, padx=3, pady=16, sticky="nsew")
        self.A03D2 = customtkinter.CTkButton(self.A_frame1, text='A03D2', command=self.sidebar_button_event, width=15)
        self.A03D2.grid(row=8, column=47, padx=3, pady=16, sticky="nsew")
        
        self.A06A1 = customtkinter.CTkButton(self.A_frame2, text='A06A1', command=self.sidebar_button_event, width=15)
        self.A06A1.grid(row=10, column=45, padx=3, pady=16, sticky="nsew")
        self.A06A2 = customtkinter.CTkButton(self.A_frame2, text='A06A2', command=self.sidebar_button_event, width=15)
        self.A06A2.grid(row=11, column=45, padx=3, pady=16, sticky="nsew")
        self.A06B1 = customtkinter.CTkButton(self.A_frame2, text='A06B1', command=self.sidebar_button_event, width=15)
        self.A06B1.grid(row=12, column=45, padx=3, pady=16, sticky="nsew")
        self.A06B2 = customtkinter.CTkButton(self.A_frame2, text='A06B2', command=self.sidebar_button_event, width=15)
        self.A06B2.grid(row=13, column=45, padx=3, pady=16, sticky="nsew")
        self.A06C1 = customtkinter.CTkButton(self.A_frame2, text='A06C1', command=self.sidebar_button_event, width=15)
        self.A06C1.grid(row=14, column=45, padx=3, pady=16, sticky="nsew")
        self.A06C2 = customtkinter.CTkButton(self.A_frame2, text='A06C2', command=self.sidebar_button_event, width=15)
        self.A06C2.grid(row=15, column=45, padx=3, pady=16, sticky="nsew")
        self.A06D1 = customtkinter.CTkButton(self.A_frame2, text='A06D1', command=self.sidebar_button_event, width=15)
        self.A06D1.grid(row=16, column=45, padx=3, pady=16, sticky="nsew")
        self.A06D2 = customtkinter.CTkButton(self.A_frame2, text='A06D2', command=self.sidebar_button_event, width=15)
        self.A06D2.grid(row=17, column=45, padx=3, pady=16, sticky="nsew")
        
        self.A07A1 = customtkinter.CTkButton(self.A_frame2, text='A07A1', command=self.sidebar_button_event, width=15)
        self.A07A1.grid(row=10, column=46, padx=3, pady=16, sticky="nsew")
        self.A07A2 = customtkinter.CTkButton(self.A_frame2, text='A07A2', command=self.sidebar_button_event, width=15)
        self.A07A2.grid(row=11, column=46, padx=3, pady=16, sticky="nsew")
        self.A07B1 = customtkinter.CTkButton(self.A_frame2, text='A07B1', command=self.sidebar_button_event, width=15)
        self.A07B1.grid(row=12, column=46, padx=3, pady=16, sticky="nsew")
        self.A07B2 = customtkinter.CTkButton(self.A_frame2, text='A07B2', command=self.sidebar_button_event, width=15)
        self.A07B2.grid(row=13, column=46, padx=3, pady=16, sticky="nsew")
        self.A07C1 = customtkinter.CTkButton(self.A_frame2, text='A07C1', command=self.sidebar_button_event, width=15)
        self.A07C1.grid(row=14, column=46, padx=3, pady=16, sticky="nsew")
        self.A07C2 = customtkinter.CTkButton(self.A_frame2, text='A07C2', command=self.sidebar_button_event, width=15)
        self.A07C2.grid(row=15, column=46, padx=3, pady=16, sticky="nsew")
        self.A07D1 = customtkinter.CTkButton(self.A_frame2, text='A07D1', command=self.sidebar_button_event, width=15)
        self.A07D1.grid(row=16, column=46, padx=3, pady=16, sticky="nsew")
        self.A07D2 = customtkinter.CTkButton(self.A_frame2, text='A07D2', command=self.sidebar_button_event, width=15)
        self.A07D2.grid(row=17, column=46, padx=3, pady=16, sticky="nsew")
        
        self.A08A1 = customtkinter.CTkButton(self.A_frame2, text='A08A1', command=self.sidebar_button_event, width=15)
        self.A08A1.grid(row=10, column=47, padx=3, pady=16, sticky="nsew")
        self.A08A2 = customtkinter.CTkButton(self.A_frame2, text='A08A2', command=self.sidebar_button_event, width=15)
        self.A08A2.grid(row=11, column=47, padx=3, pady=16, sticky="nsew")
        self.A08B1 = customtkinter.CTkButton(self.A_frame2, text='A08B1', command=self.sidebar_button_event, width=15)
        self.A08B1.grid(row=12, column=47, padx=3, pady=16, sticky="nsew")
        self.A08B2 = customtkinter.CTkButton(self.A_frame2, text='A08B2', command=self.sidebar_button_event, width=15)
        self.A08B2.grid(row=13, column=47, padx=3, pady=16, sticky="nsew")
        self.A08C1 = customtkinter.CTkButton(self.A_frame2, text='A08C1', command=self.sidebar_button_event, width=15)
        self.A08C1.grid(row=14, column=47, padx=3, pady=16, sticky="nsew")
        self.A08C2 = customtkinter.CTkButton(self.A_frame2, text='A08C2', command=self.sidebar_button_event, width=15)
        self.A08C2.grid(row=15, column=47, padx=3, pady=16, sticky="nsew")
        self.A08D1 = customtkinter.CTkButton(self.A_frame2, text='A08D1', command=self.sidebar_button_event, width=15)
        self.A08D1.grid(row=16, column=47, padx=3, pady=16, sticky="nsew")
        self.A08D2 = customtkinter.CTkButton(self.A_frame2, text='A08D2', command=self.sidebar_button_event, width=15)
        self.A08D2.grid(row=17, column=47, padx=3, pady=16, sticky="nsew")
        
        # B
        self.B01A1 = customtkinter.CTkButton(self.B_frame1, text='B01A1', command=self.sidebar_button_event, width=15)
        self.B01A1.grid(row=1, column=41, padx=3, pady=16, sticky="nsew")
        self.B01A2 = customtkinter.CTkButton(self.B_frame1, text='B01A2', command=self.sidebar_button_event, width=15)
        self.B01A2.grid(row=2, column=41, padx=3, pady=16, sticky="nsew")
        self.B01B1 = customtkinter.CTkButton(self.B_frame1, text='B01B1', command=self.sidebar_button_event, width=15)
        self.B01B1.grid(row=3, column=41, padx=3, pady=16, sticky="nsew")
        self.B01B2 = customtkinter.CTkButton(self.B_frame1, text='B01B2', command=self.sidebar_button_event, width=15)
        self.B01B2.grid(row=4, column=41, padx=3, pady=16, sticky="nsew")
        self.B01C1 = customtkinter.CTkButton(self.B_frame1, text='B01C1', command=self.sidebar_button_event, width=15)
        self.B01C1.grid(row=5, column=41, padx=3, pady=16, sticky="nsew")
        self.B01C2 = customtkinter.CTkButton(self.B_frame1, text='B01C2', command=self.sidebar_button_event, width=15)
        self.B01C2.grid(row=6, column=41, padx=3, pady=16, sticky="nsew")
        self.B01D1 = customtkinter.CTkButton(self.B_frame1, text='B01D1', command=self.sidebar_button_event, width=15)
        self.B01D1.grid(row=7, column=41, padx=3, pady=16, sticky="nsew")
        self.B01D2 = customtkinter.CTkButton(self.B_frame1, text='B01D2', command=self.sidebar_button_event, width=15)
        self.B01D2.grid(row=8, column=41, padx=3, pady=16, sticky="nsew")
        
        self.B02A1 = customtkinter.CTkButton(self.B_frame1, text='B02A1', command=self.sidebar_button_event, width=15)
        self.B02A1.grid(row=1, column=42, padx=3, pady=16, sticky="nsew")
        self.B02A2 = customtkinter.CTkButton(self.B_frame1, text='B02A2', command=self.sidebar_button_event, width=15)
        self.B02A2.grid(row=2, column=42, padx=3, pady=16, sticky="nsew")
        self.B02B1 = customtkinter.CTkButton(self.B_frame1, text='B02B1', command=self.sidebar_button_event, width=15)
        self.B02B1.grid(row=3, column=42, padx=3, pady=16, sticky="nsew")
        self.B02B2 = customtkinter.CTkButton(self.B_frame1, text='B02B2', command=self.sidebar_button_event, width=15)
        self.B02B2.grid(row=4, column=42, padx=3, pady=16, sticky="nsew")
        self.B02C1 = customtkinter.CTkButton(self.B_frame1, text='B02C1', command=self.sidebar_button_event, width=15)
        self.B02C1.grid(row=5, column=42, padx=3, pady=16, sticky="nsew")
        self.B02C2 = customtkinter.CTkButton(self.B_frame1, text='B02C2', command=self.sidebar_button_event, width=15)
        self.B02C2.grid(row=6, column=42, padx=3, pady=16, sticky="nsew")
        self.B02D1 = customtkinter.CTkButton(self.B_frame1, text='B02D1', command=self.sidebar_button_event, width=15)
        self.B02D1.grid(row=7, column=42, padx=3, pady=16, sticky="nsew")
        self.B02D2 = customtkinter.CTkButton(self.B_frame1, text='B02D2', command=self.sidebar_button_event, width=15)
        self.B02D2.grid(row=8, column=42, padx=3, pady=16, sticky="nsew")
        
        self.B03A1 = customtkinter.CTkButton(self.B_frame1, text='B03A1', command=self.sidebar_button_event, width=15)
        self.B03A1.grid(row=1, column=43, padx=3, pady=16, sticky="nsew")
        self.B03A2 = customtkinter.CTkButton(self.B_frame1, text='B03A2', command=self.sidebar_button_event, width=15)
        self.B03A2.grid(row=2, column=43, padx=3, pady=16, sticky="nsew")
        self.B03B1 = customtkinter.CTkButton(self.B_frame1, text='B03B1', command=self.sidebar_button_event, width=15)
        self.B03B1.grid(row=3, column=43, padx=3, pady=16, sticky="nsew")
        self.B03B2 = customtkinter.CTkButton(self.B_frame1, text='B03B2', command=self.sidebar_button_event, width=15)
        self.B03B2.grid(row=4, column=43, padx=3, pady=16, sticky="nsew")
        self.B03C1 = customtkinter.CTkButton(self.B_frame1, text='B03C1', command=self.sidebar_button_event, width=15)
        self.B03C1.grid(row=5, column=43, padx=3, pady=16, sticky="nsew")
        self.B03C2 = customtkinter.CTkButton(self.B_frame1, text='B03C2', command=self.sidebar_button_event, width=15)
        self.B03C2.grid(row=6, column=43, padx=3, pady=16, sticky="nsew")
        self.B03D1 = customtkinter.CTkButton(self.B_frame1, text='B03D1', command=self.sidebar_button_event, width=15)
        self.B03D1.grid(row=7, column=43, padx=3, pady=16, sticky="nsew")
        self.B03D2 = customtkinter.CTkButton(self.B_frame1, text='B03D2', command=self.sidebar_button_event, width=15)
        self.B03D2.grid(row=8, column=43, padx=3, pady=16, sticky="nsew")
        
        self.B06A1 = customtkinter.CTkButton(self.B_frame2, text='B06A1', command=self.sidebar_button_event, width=15)
        self.B06A1.grid(row=10, column=41, padx=3, pady=16, sticky="nsew")
        self.B06A2 = customtkinter.CTkButton(self.B_frame2, text='B06A2', command=self.sidebar_button_event, width=15)
        self.B06A2.grid(row=11, column=41, padx=3, pady=16, sticky="nsew")
        self.B06B1 = customtkinter.CTkButton(self.B_frame2, text='B06B1', command=self.sidebar_button_event, width=15)
        self.B06B1.grid(row=12, column=41, padx=3, pady=16, sticky="nsew")
        self.B06B2 = customtkinter.CTkButton(self.B_frame2, text='B06B2', command=self.sidebar_button_event, width=15)
        self.B06B2.grid(row=13, column=41, padx=3, pady=16, sticky="nsew")
        self.B06C1 = customtkinter.CTkButton(self.B_frame2, text='B06C1', command=self.sidebar_button_event, width=15)
        self.B06C1.grid(row=14, column=41, padx=3, pady=16, sticky="nsew")
        self.B06C2 = customtkinter.CTkButton(self.B_frame2, text='B06C2', command=self.sidebar_button_event, width=15)
        self.B06C2.grid(row=15, column=41, padx=3, pady=16, sticky="nsew")
        self.B06D1 = customtkinter.CTkButton(self.B_frame2, text='B06D1', command=self.sidebar_button_event, width=15)
        self.B06D1.grid(row=16, column=41, padx=3, pady=16, sticky="nsew")
        self.B06D2 = customtkinter.CTkButton(self.B_frame2, text='B06D2', command=self.sidebar_button_event, width=15)
        self.B06D2.grid(row=17, column=41, padx=3, pady=16, sticky="nsew")
        
        self.B07A1 = customtkinter.CTkButton(self.B_frame2, text='B07A1', command=self.sidebar_button_event, width=15)
        self.B07A1.grid(row=10, column=42, padx=3, pady=16, sticky="nsew")
        self.B07A2 = customtkinter.CTkButton(self.B_frame2, text='B07A2', command=self.sidebar_button_event, width=15)
        self.B07A2.grid(row=11, column=42, padx=3, pady=16, sticky="nsew")
        self.B07B1 = customtkinter.CTkButton(self.B_frame2, text='B07B1', command=self.sidebar_button_event, width=15)
        self.B07B1.grid(row=12, column=42, padx=3, pady=16, sticky="nsew")
        self.B07B2 = customtkinter.CTkButton(self.B_frame2, text='B07B2', command=self.sidebar_button_event, width=15)
        self.B07B2.grid(row=13, column=42, padx=3, pady=16, sticky="nsew")
        self.B07C1 = customtkinter.CTkButton(self.B_frame2, text='B07C1', command=self.sidebar_button_event, width=15)
        self.B07C1.grid(row=14, column=42, padx=3, pady=16, sticky="nsew")
        self.B07C2 = customtkinter.CTkButton(self.B_frame2, text='B07C2', command=self.sidebar_button_event, width=15)
        self.B07C2.grid(row=15, column=42, padx=3, pady=16, sticky="nsew")
        self.B07D1 = customtkinter.CTkButton(self.B_frame2, text='B07D1', command=self.sidebar_button_event, width=15)
        self.B07D1.grid(row=16, column=42, padx=3, pady=16, sticky="nsew")
        self.B07D2 = customtkinter.CTkButton(self.B_frame2, text='B07D2', command=self.sidebar_button_event, width=15)
        self.B07D2.grid(row=17, column=42, padx=3, pady=16, sticky="nsew")
        
        self.B08A1 = customtkinter.CTkButton(self.B_frame2, text='B08A1', command=self.sidebar_button_event, width=15)
        self.B08A1.grid(row=10, column=43, padx=3, pady=16, sticky="nsew")
        self.B08A2 = customtkinter.CTkButton(self.B_frame2, text='B08A2', command=self.sidebar_button_event, width=15)
        self.B08A2.grid(row=11, column=43, padx=3, pady=16, sticky="nsew")
        self.B08B1 = customtkinter.CTkButton(self.B_frame2, text='B08B1', command=self.sidebar_button_event, width=15)
        self.B08B1.grid(row=12, column=43, padx=3, pady=16, sticky="nsew")
        self.B08B2 = customtkinter.CTkButton(self.B_frame2, text='B08B2', command=self.sidebar_button_event, width=15)
        self.B08B2.grid(row=13, column=43, padx=3, pady=16, sticky="nsew")
        self.B08C1 = customtkinter.CTkButton(self.B_frame2, text='B08C1', command=self.sidebar_button_event, width=15)
        self.B08C1.grid(row=14, column=43, padx=3, pady=16, sticky="nsew")
        self.B08C2 = customtkinter.CTkButton(self.B_frame2, text='B08C2', command=self.sidebar_button_event, width=15)
        self.B08C2.grid(row=15, column=43, padx=3, pady=16, sticky="nsew")
        self.B08D1 = customtkinter.CTkButton(self.B_frame2, text='B08D1', command=self.sidebar_button_event, width=15)
        self.B08D1.grid(row=16, column=43, padx=3, pady=16, sticky="nsew")
        self.B08D2 = customtkinter.CTkButton(self.B_frame2, text='B08D2', command=self.sidebar_button_event, width=15)
        self.B08D2.grid(row=17, column=43, padx=3, pady=16, sticky="nsew")
        
        # C
        self.C01A1 = customtkinter.CTkButton(self.C_frame1, text='C01A1', command=self.sidebar_button_event, width=15)
        self.C01A1.grid(row=1, column=38, padx=3, pady=16, sticky="nsew")
        self.C01A2 = customtkinter.CTkButton(self.C_frame1, text='C01A2', command=self.sidebar_button_event, width=15)
        self.C01A2.grid(row=2, column=38, padx=3, pady=16, sticky="nsew")
        self.C01B1 = customtkinter.CTkButton(self.C_frame1, text='C01B1', command=self.sidebar_button_event, width=15)
        self.C01B1.grid(row=3, column=38, padx=3, pady=16, sticky="nsew")
        self.C01B2 = customtkinter.CTkButton(self.C_frame1, text='C01B2', command=self.sidebar_button_event, width=15)
        self.C01B2.grid(row=4, column=38, padx=3, pady=16, sticky="nsew")
        self.C01C1 = customtkinter.CTkButton(self.C_frame1, text='C01C1', command=self.sidebar_button_event, width=15)
        self.C01C1.grid(row=5, column=38, padx=3, pady=16, sticky="nsew")
        self.C01C2 = customtkinter.CTkButton(self.C_frame1, text='C01C2', command=self.sidebar_button_event, width=15)
        self.C01C2.grid(row=6, column=38, padx=3, pady=16, sticky="nsew")
        self.C01D1 = customtkinter.CTkButton(self.C_frame1, text='C01D1', command=self.sidebar_button_event, width=15)
        self.C01D1.grid(row=7, column=38, padx=3, pady=16, sticky="nsew")
        self.C01D2 = customtkinter.CTkButton(self.C_frame1, text='C01D2', command=self.sidebar_button_event, width=15)
        self.C01D2.grid(row=8, column=38, padx=3, pady=16, sticky="nsew")
        
        self.C02A1 = customtkinter.CTkButton(self.C_frame1, text='C02A1', command=self.sidebar_button_event, width=15)
        self.C02A1.grid(row=1, column=39, padx=3, pady=16, sticky="nsew")
        self.C02A2 = customtkinter.CTkButton(self.C_frame1, text='C02A2', command=self.sidebar_button_event, width=15)
        self.C02A2.grid(row=2, column=39, padx=3, pady=16, sticky="nsew")
        self.C02B1 = customtkinter.CTkButton(self.C_frame1, text='C02B1', command=self.sidebar_button_event, width=15)
        self.C02B1.grid(row=3, column=39, padx=3, pady=16, sticky="nsew")
        self.C02B2 = customtkinter.CTkButton(self.C_frame1, text='C02B2', command=self.sidebar_button_event, width=15)
        self.C02B2.grid(row=4, column=39, padx=3, pady=16, sticky="nsew")
        self.C02C1 = customtkinter.CTkButton(self.C_frame1, text='C02C1', command=self.sidebar_button_event, width=15)
        self.C02C1.grid(row=5, column=39, padx=3, pady=16, sticky="nsew")
        self.C02C2 = customtkinter.CTkButton(self.C_frame1, text='C02C2', command=self.sidebar_button_event, width=15)
        self.C02C2.grid(row=6, column=39, padx=3, pady=16, sticky="nsew")
        self.C02D1 = customtkinter.CTkButton(self.C_frame1, text='C02D1', command=self.sidebar_button_event, width=15)
        self.C02D1.grid(row=7, column=39, padx=3, pady=16, sticky="nsew")
        self.C02D2 = customtkinter.CTkButton(self.C_frame1, text='C02D2', command=self.sidebar_button_event, width=15)
        self.C02D2.grid(row=8, column=39, padx=3, pady=16, sticky="nsew")
        
        self.C03A1 = customtkinter.CTkButton(self.C_frame1, text='C03A1', command=self.sidebar_button_event, width=15)
        self.C03A1.grid(row=1, column=40, padx=3, pady=16, sticky="nsew")
        self.C03A2 = customtkinter.CTkButton(self.C_frame1, text='C03A2', command=self.sidebar_button_event, width=15)
        self.C03A2.grid(row=2, column=40, padx=3, pady=16, sticky="nsew")
        self.C03B1 = customtkinter.CTkButton(self.C_frame1, text='C03B1', command=self.sidebar_button_event, width=15)
        self.C03B1.grid(row=3, column=40, padx=3, pady=16, sticky="nsew")
        self.C03B2 = customtkinter.CTkButton(self.C_frame1, text='C03B2', command=self.sidebar_button_event, width=15)
        self.C03B2.grid(row=4, column=40, padx=3, pady=16, sticky="nsew")
        self.C03C1 = customtkinter.CTkButton(self.C_frame1, text='C03C1', command=self.sidebar_button_event, width=15)
        self.C03C1.grid(row=5, column=40, padx=3, pady=16, sticky="nsew")
        self.C03C2 = customtkinter.CTkButton(self.C_frame1, text='C03C2', command=self.sidebar_button_event, width=15)
        self.C03C2.grid(row=6, column=40, padx=3, pady=16, sticky="nsew")
        self.C03D1 = customtkinter.CTkButton(self.C_frame1, text='C03D1', command=self.sidebar_button_event, width=15)
        self.C03D1.grid(row=7, column=40, padx=3, pady=16, sticky="nsew")
        self.C03D2 = customtkinter.CTkButton(self.C_frame1, text='C03D2', command=self.sidebar_button_event, width=15)
        self.C03D2.grid(row=8, column=40, padx=3, pady=16, sticky="nsew")
        
        self.C06A1 = customtkinter.CTkButton(self.C_frame2, text='C06A1', command=self.sidebar_button_event, width=15)
        self.C06A1.grid(row=10, column=38, padx=3, pady=16, sticky="nsew")
        self.C06A2 = customtkinter.CTkButton(self.C_frame2, text='C06A2', command=self.sidebar_button_event, width=15)
        self.C06A2.grid(row=11, column=38, padx=3, pady=16, sticky="nsew")
        self.C06B1 = customtkinter.CTkButton(self.C_frame2, text='C06B1', command=self.sidebar_button_event, width=15)
        self.C06B1.grid(row=12, column=38, padx=3, pady=16, sticky="nsew")
        self.C06B2 = customtkinter.CTkButton(self.C_frame2, text='C06B2', command=self.sidebar_button_event, width=15)
        self.C06B2.grid(row=13, column=38, padx=3, pady=16, sticky="nsew")
        self.C06C1 = customtkinter.CTkButton(self.C_frame2, text='C06C1', command=self.sidebar_button_event, width=15)
        self.C06C1.grid(row=14, column=38, padx=3, pady=16, sticky="nsew")
        self.C06C2 = customtkinter.CTkButton(self.C_frame2, text='C06C2', command=self.sidebar_button_event, width=15)
        self.C06C2.grid(row=15, column=38, padx=3, pady=16, sticky="nsew")
        self.C06D1 = customtkinter.CTkButton(self.C_frame2, text='C06D1', command=self.sidebar_button_event, width=15)
        self.C06D1.grid(row=16, column=38, padx=3, pady=16, sticky="nsew")
        self.C06D2 = customtkinter.CTkButton(self.C_frame2, text='C06D2', command=self.sidebar_button_event, width=15)
        self.C06D2.grid(row=17, column=38, padx=3, pady=16, sticky="nsew")
        
        self.C07A1 = customtkinter.CTkButton(self.C_frame2, text='C07A1', command=self.sidebar_button_event, width=15)
        self.C07A1.grid(row=10, column=39, padx=3, pady=16, sticky="nsew")
        self.C07A2 = customtkinter.CTkButton(self.C_frame2, text='C07A2', command=self.sidebar_button_event, width=15)
        self.C07A2.grid(row=11, column=39, padx=3, pady=16, sticky="nsew")
        self.C07B1 = customtkinter.CTkButton(self.C_frame2, text='C07B1', command=self.sidebar_button_event, width=15)
        self.C07B1.grid(row=12, column=39, padx=3, pady=16, sticky="nsew")
        self.C07B2 = customtkinter.CTkButton(self.C_frame2, text='C07B2', command=self.sidebar_button_event, width=15)
        self.C07B2.grid(row=13, column=39, padx=3, pady=16, sticky="nsew")
        self.C07C1 = customtkinter.CTkButton(self.C_frame2, text='C07C1', command=self.sidebar_button_event, width=15)
        self.C07C1.grid(row=14, column=39, padx=3, pady=16, sticky="nsew")
        self.C07C2 = customtkinter.CTkButton(self.C_frame2, text='C07C2', command=self.sidebar_button_event, width=15)
        self.C07C2.grid(row=15, column=39, padx=3, pady=16, sticky="nsew")
        self.C07D1 = customtkinter.CTkButton(self.C_frame2, text='C07D1', command=self.sidebar_button_event, width=15)
        self.C07D1.grid(row=16, column=39, padx=3, pady=16, sticky="nsew")
        self.C07D2 = customtkinter.CTkButton(self.C_frame2, text='C07D2', command=self.sidebar_button_event, width=15)
        self.C07D2.grid(row=17, column=39, padx=3, pady=16, sticky="nsew")
        
        self.C08A1 = customtkinter.CTkButton(self.C_frame2, text='C08A1', command=self.sidebar_button_event, width=15)
        self.C08A1.grid(row=10, column=40, padx=3, pady=16, sticky="nsew")
        self.C08A2 = customtkinter.CTkButton(self.C_frame2, text='C08A2', command=self.sidebar_button_event, width=15)
        self.C08A2.grid(row=11, column=40, padx=3, pady=16, sticky="nsew")
        self.C08B1 = customtkinter.CTkButton(self.C_frame2, text='C08B1', command=self.sidebar_button_event, width=15)
        self.C08B1.grid(row=12, column=40, padx=3, pady=16, sticky="nsew")
        self.C08B2 = customtkinter.CTkButton(self.C_frame2, text='C08B2', command=self.sidebar_button_event, width=15)
        self.C08B2.grid(row=13, column=40, padx=3, pady=16, sticky="nsew")
        self.C08C1 = customtkinter.CTkButton(self.C_frame2, text='C08C1', command=self.sidebar_button_event, width=15)
        self.C08C1.grid(row=14, column=40, padx=3, pady=16, sticky="nsew")
        self.C08C2 = customtkinter.CTkButton(self.C_frame2, text='C08C2', command=self.sidebar_button_event, width=15)
        self.C08C2.grid(row=15, column=40, padx=3, pady=16, sticky="nsew")
        self.C08D1 = customtkinter.CTkButton(self.C_frame2, text='C08D1', command=self.sidebar_button_event, width=15)
        self.C08D1.grid(row=16, column=40, padx=3, pady=16, sticky="nsew")
        self.C08D2 = customtkinter.CTkButton(self.C_frame2, text='C08D2', command=self.sidebar_button_event, width=15)
        self.C08D2.grid(row=17, column=40, padx=3, pady=16, sticky="nsew")
        
         # D
        self.D01A1 = customtkinter.CTkButton(self.D_frame1, text='D01A1', command=self.sidebar_button_event, width=15)
        self.D01A1.grid(row=1, column=35, padx=3, pady=16, sticky="nsew")
        self.D01A2 = customtkinter.CTkButton(self.D_frame1, text='D01A2', command=self.sidebar_button_event, width=15)
        self.D01A2.grid(row=2, column=35, padx=3, pady=16, sticky="nsew")
        self.D01B1 = customtkinter.CTkButton(self.D_frame1, text='D01B1', command=self.sidebar_button_event, width=15)
        self.D01B1.grid(row=3, column=35, padx=3, pady=16, sticky="nsew")
        self.D01B2 = customtkinter.CTkButton(self.D_frame1, text='D01B2', command=self.sidebar_button_event, width=15)
        self.D01B2.grid(row=4, column=35, padx=3, pady=16, sticky="nsew")
        self.D01C1 = customtkinter.CTkButton(self.D_frame1, text='D01C1', command=self.sidebar_button_event, width=15)
        self.D01C1.grid(row=5, column=35, padx=3, pady=16, sticky="nsew")
        self.D01C2 = customtkinter.CTkButton(self.D_frame1, text='D01C2', command=self.sidebar_button_event, width=15)
        self.D01C2.grid(row=6, column=35, padx=3, pady=16, sticky="nsew")
        self.D01D1 = customtkinter.CTkButton(self.D_frame1, text='D01D1', command=self.sidebar_button_event, width=15)
        self.D01D1.grid(row=7, column=35, padx=3, pady=16, sticky="nsew")
        self.D01D2 = customtkinter.CTkButton(self.D_frame1, text='D01D2', command=self.sidebar_button_event, width=15)
        self.D01D2.grid(row=8, column=35, padx=3, pady=16, sticky="nsew")
        
        self.D02A1 = customtkinter.CTkButton(self.D_frame1, text='D02A1', command=self.sidebar_button_event, width=15)
        self.D02A1.grid(row=1, column=36, padx=3, pady=16, sticky="nsew")
        self.D02A2 = customtkinter.CTkButton(self.D_frame1, text='D02A2', command=self.sidebar_button_event, width=15)
        self.D02A2.grid(row=2, column=36, padx=3, pady=16, sticky="nsew")
        self.D02B1 = customtkinter.CTkButton(self.D_frame1, text='D02B1', command=self.sidebar_button_event, width=15)
        self.D02B1.grid(row=3, column=36, padx=3, pady=16, sticky="nsew")
        self.D02B2 = customtkinter.CTkButton(self.D_frame1, text='D02B2', command=self.sidebar_button_event, width=15)
        self.D02B2.grid(row=4, column=36, padx=3, pady=16, sticky="nsew")
        self.D02C1 = customtkinter.CTkButton(self.D_frame1, text='D02C1', command=self.sidebar_button_event, width=15)
        self.D02C1.grid(row=5, column=36, padx=3, pady=16, sticky="nsew")
        self.D02C2 = customtkinter.CTkButton(self.D_frame1, text='D02C2', command=self.sidebar_button_event, width=15)
        self.D02C2.grid(row=6, column=36, padx=3, pady=16, sticky="nsew")
        self.D02D1 = customtkinter.CTkButton(self.D_frame1, text='D02D1', command=self.sidebar_button_event, width=15)
        self.D02D1.grid(row=7, column=36, padx=3, pady=16, sticky="nsew")
        self.D02D2 = customtkinter.CTkButton(self.D_frame1, text='D02D2', command=self.sidebar_button_event, width=15)
        self.D02D2.grid(row=8, column=36, padx=3, pady=16, sticky="nsew")
        
        self.D03A1 = customtkinter.CTkButton(self.D_frame1, text='D03A1', command=self.sidebar_button_event, width=15)
        self.D03A1.grid(row=1, column=37, padx=3, pady=16, sticky="nsew")
        self.D03A2 = customtkinter.CTkButton(self.D_frame1, text='D03A2', command=self.sidebar_button_event, width=15)
        self.D03A2.grid(row=2, column=37, padx=3, pady=16, sticky="nsew")
        self.D03B1 = customtkinter.CTkButton(self.D_frame1, text='D03B1', command=self.sidebar_button_event, width=15)
        self.D03B1.grid(row=3, column=37, padx=3, pady=16, sticky="nsew")
        self.D03B2 = customtkinter.CTkButton(self.D_frame1, text='D03B2', command=self.sidebar_button_event, width=15)
        self.D03B2.grid(row=4, column=37, padx=3, pady=16, sticky="nsew")
        self.D03C1 = customtkinter.CTkButton(self.D_frame1, text='D03C1', command=self.sidebar_button_event, width=15)
        self.D03C1.grid(row=5, column=37, padx=3, pady=16, sticky="nsew")
        self.D03C2 = customtkinter.CTkButton(self.D_frame1, text='D03C2', command=self.sidebar_button_event, width=15)
        self.D03C2.grid(row=6, column=37, padx=3, pady=16, sticky="nsew")
        self.D03D1 = customtkinter.CTkButton(self.D_frame1, text='D03D1', command=self.sidebar_button_event, width=15)
        self.D03D1.grid(row=7, column=37, padx=3, pady=16, sticky="nsew")
        self.D03D2 = customtkinter.CTkButton(self.D_frame1, text='D03D2', command=self.sidebar_button_event, width=15)
        self.D03D2.grid(row=8, column=37, padx=3, pady=16, sticky="nsew")
        
        self.D06A1 = customtkinter.CTkButton(self.D_frame2, text='D06A1', command=self.sidebar_button_event, width=15)
        self.D06A1.grid(row=10, column=35, padx=3, pady=16, sticky="nsew")
        self.D06A2 = customtkinter.CTkButton(self.D_frame2, text='D06A2', command=self.sidebar_button_event, width=15)
        self.D06A2.grid(row=11, column=35, padx=3, pady=16, sticky="nsew")
        self.D06B1 = customtkinter.CTkButton(self.D_frame2, text='D06B1', command=self.sidebar_button_event, width=15)
        self.D06B1.grid(row=12, column=35, padx=3, pady=16, sticky="nsew")
        self.D06B2 = customtkinter.CTkButton(self.D_frame2, text='D06B2', command=self.sidebar_button_event, width=15)
        self.D06B2.grid(row=13, column=35, padx=3, pady=16, sticky="nsew")
        self.D06C1 = customtkinter.CTkButton(self.D_frame2, text='D06C1', command=self.sidebar_button_event, width=15)
        self.D06C1.grid(row=14, column=35, padx=3, pady=16, sticky="nsew")
        self.D06C2 = customtkinter.CTkButton(self.D_frame2, text='D06C2', command=self.sidebar_button_event, width=15)
        self.D06C2.grid(row=15, column=35, padx=3, pady=16, sticky="nsew")
        self.D06D1 = customtkinter.CTkButton(self.D_frame2, text='D06D1', command=self.sidebar_button_event, width=15)
        self.D06D1.grid(row=16, column=35, padx=3, pady=16, sticky="nsew")
        self.D06D2 = customtkinter.CTkButton(self.D_frame2, text='D06D2', command=self.sidebar_button_event, width=15)
        self.D06D2.grid(row=17, column=35, padx=3, pady=16, sticky="nsew")
        
        self.D07A1 = customtkinter.CTkButton(self.D_frame2, text='D07A1', command=self.sidebar_button_event, width=15)
        self.D07A1.grid(row=10, column=36, padx=3, pady=16, sticky="nsew")
        self.D07A2 = customtkinter.CTkButton(self.D_frame2, text='D07A2', command=self.sidebar_button_event, width=15)
        self.D07A2.grid(row=11, column=36, padx=3, pady=16, sticky="nsew")
        self.D07B1 = customtkinter.CTkButton(self.D_frame2, text='D07B1', command=self.sidebar_button_event, width=15)
        self.D07B1.grid(row=12, column=36, padx=3, pady=16, sticky="nsew")
        self.D07B2 = customtkinter.CTkButton(self.D_frame2, text='D07B2', command=self.sidebar_button_event, width=15)
        self.D07B2.grid(row=13, column=36, padx=3, pady=16, sticky="nsew")
        self.D07C1 = customtkinter.CTkButton(self.D_frame2, text='D07C1', command=self.sidebar_button_event, width=15)
        self.D07C1.grid(row=14, column=36, padx=3, pady=16, sticky="nsew")
        self.D07C2 = customtkinter.CTkButton(self.D_frame2, text='D07C2', command=self.sidebar_button_event, width=15)
        self.D07C2.grid(row=15, column=36, padx=3, pady=16, sticky="nsew")
        self.D07D1 = customtkinter.CTkButton(self.D_frame2, text='D07D1', command=self.sidebar_button_event, width=15)
        self.D07D1.grid(row=16, column=36, padx=3, pady=16, sticky="nsew")
        self.D07D2 = customtkinter.CTkButton(self.D_frame2, text='D07D2', command=self.sidebar_button_event, width=15)
        self.D07D2.grid(row=17, column=36, padx=3, pady=16, sticky="nsew")
        
        self.D08A1 = customtkinter.CTkButton(self.D_frame2, text='D08A1', command=self.sidebar_button_event, width=15)
        self.D08A1.grid(row=10, column=37, padx=3, pady=16, sticky="nsew")
        self.D08A2 = customtkinter.CTkButton(self.D_frame2, text='D08A2', command=self.sidebar_button_event, width=15)
        self.D08A2.grid(row=11, column=37, padx=3, pady=16, sticky="nsew")
        self.D08B1 = customtkinter.CTkButton(self.D_frame2, text='D08B1', command=self.sidebar_button_event, width=15)
        self.D08B1.grid(row=12, column=37, padx=3, pady=16, sticky="nsew")
        self.D08B2 = customtkinter.CTkButton(self.D_frame2, text='D08B2', command=self.sidebar_button_event, width=15)
        self.D08B2.grid(row=13, column=37, padx=3, pady=16, sticky="nsew")
        self.D08C1 = customtkinter.CTkButton(self.D_frame2, text='D08C1', command=self.sidebar_button_event, width=15)
        self.D08C1.grid(row=14, column=37, padx=3, pady=16, sticky="nsew")
        self.D08C2 = customtkinter.CTkButton(self.D_frame2, text='D08C2', command=self.sidebar_button_event, width=15)
        self.D08C2.grid(row=15, column=37, padx=3, pady=16, sticky="nsew")
        self.D08D1 = customtkinter.CTkButton(self.D_frame2, text='D08D1', command=self.sidebar_button_event, width=15)
        self.D08D1.grid(row=16, column=37, padx=3, pady=16, sticky="nsew")
        self.D08D2 = customtkinter.CTkButton(self.D_frame2, text='D08D2', command=self.sidebar_button_event, width=15)
        self.D08D2.grid(row=17, column=37, padx=3, pady=16, sticky="nsew")
        
    def activate_progress_bar_event(self):
        self.progressbar_1 = customtkinter.CTkProgressBar(self)
        self.progressbar_1.grid(row=6, column=1, columnspan=3, padx=(20, 10), pady=(5, 5), sticky="nsew")
        self.progressbar_1.configure(mode="indeterminnate")

        self.progressbar_1.start()

    def open_input_dialog_event(self):
        dialog = customtkinter.CTkInputDialog(text="Type in a number:", title="CTkInputDialog")
        print(("CTkInputDialog:", dialog.get_input()))

    def change_appearance_mode_event(self, new_appearance_mode: str):
        customtkinter.set_appearance_mode(new_appearance_mode)

    def change_scaling_event(self, new_scaling: str):
        new_scaling_float = int(new_scaling.replace("%", "")) / 100
        customtkinter.set_widget_scaling(new_scaling_float)

    def sidebar_button_event(self):
        print(self)

if __name__ == "__main__":
    app = App()
    app.mainloop()
